name: main_action
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - run: pip install cpplint
    - run: cpplint --linelength=120 --extensions=hpp,cpp,h,c,ino --recursive .
  arduino_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: arduino/arduino-lint-action@v3
        with:
          library-manager: 'update'
  build_ESP32:
    needs: [cpplint, arduino_lint]
    runs-on: ubuntu-latest
    env:
        SKETCH_NAME: ESP_Blink_jQuery_Mobile_Frontend
        CORE: esp32
        BOARD: d1_mini32
    steps:
      - uses: actions/checkout@v7
      - uses: hredan/eep-build-action@switch-to-python
        with:
          sketch-name: ${{env.SKETCH_NAME}}
          core: ${{env.CORE}}
          board: ${{env.BOARD}}
  build_ESP8266:
    needs: [cpplint, arduino_lint]
    runs-on: ubuntu-latest
    env:
        SKETCH_NAME: ESP_Blink_jQuery_Mobile_Frontend
        CORE: esp8266
        BOARD: d1_mini
    steps:
      - uses: actions/checkout@v7
      - uses: hredan/eep-build-action@switch-to-python
        with:
          sketch-name: ${{env.SKETCH_NAME}}
          core: ${{env.CORE}}
          board: ${{env.BOARD}}
          cpu-frequency: 160

          
